name: Run TSX Script

on:
  workflow_dispatch: # manual trigger via GitHub UI
  schedule:
    - cron: "0 */8 * * *" # runs every 8 hours

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Puppeteer system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          libx11-xcb1 libxcomposite1 libxdamage1 libxrandr2 libgtk-3-0 \
          libgbm1 libnss3 libasound2t64 libatk1.0-0 libatk-bridge2.0-0 \
          libdrm2 libxext6 libxfixes3 libxrender1 libxcb1 libxcursor1 \
          libxinerama1 libpango-1.0-0 libcups2 libdbus-1-3 \
          libgdk-pixbuf2.0-0 libglib2.0-0 libxss1 fonts-liberation

      - name: Run main script
        run: npx tsx src/index.ts
        env:
          NOTION_TOKEN: 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
          NOTION_DATABASE_ID: 22f63fff-f2d6-80b4-93f8-ce1dc495aefa
