name: Run TSX Script

on:
  workflow_dispatch: # allows manual trigger from GitHub UI
  schedule:
    - cron: "0 * * * *" # runs every hour

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run test-notion.ts script
        run: npx tsx src/test-notion.ts
        env:
          NOTION_TOKEN: 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
          NOTION_DATABASE_ID: 22f63fff-f2d6-80b4-93f8-ce1dc495aefa
